2024-11-23 06:32:29,485 - ERROR - Initialization failed: [Errno 2] No such file or directory: '/etc/py1090dumpfa/receiverlocation.json'
2024-11-23 06:34:43,054 - ERROR - Error fetching aircraft data: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /skyaware/data/aircraft.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9803e54208>: Failed to establish a new connection: [Errno 111] Connection refused',))
2024-11-23 06:34:43,055 - ERROR - Error fetching aircraft data: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /skyaware/data/aircraft.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9803e54ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2024-11-23 06:36:43,215 - ERROR - Error fetching aircraft data: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /skyaware/data/aircraft.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72416504a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2024-11-23 06:36:43,216 - ERROR - Error fetching aircraft data: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /skyaware/data/aircraft.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7241650d68>: Failed to establish a new connection: [Errno 111] Connection refused',))
2024-11-23 22:08:42,383 - WARNING - No aircraft found with 'category' in ['A4'].
